### ISSUE TITLE
mod.info not found

### ISSUE THREAD

**Issue by vavavr00m** [poynty/ArkCodeGeneratorRedux#2]
\SteamLibrary\steamapps\common\ARK\ShooterGame\Content\PrimalEarth\CoreBlueprints

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\ARK\ShooterGame\Content\PrimalEarth\CoreBlueprints\mod.info'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at McTash.ArkCodeGeneratorRedux.ACGR.Main(String[] args)

**Comment by poynty** [comment]
Hmm, mod.info is how I get the mod name. I'll do a fix soon but it might not get the mod name for mods without that file. Oh wait, I don't think that is a mod folder.

**Comment by vavavr00m** [comment]
Correct. It's the vanilla folders.

**Comment by poynty** [comment]
Will see if I can get this working in the re-write. This program is just for the mods folder.
